# Filtros y selecciones en Pandas

## Importamos Dataset y hacemos un EDA

In [2]:
# Importar la librería Pandas
import pandas as pd

In [4]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# Importamos el Dataset Netflix
df = pd.read_csv("/content/drive/MyDrive/datasets/netflix_titles.csv")

In [6]:
# Ver información general del Dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
# Ver los primeros registros
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [13]:
# Rápida exploración de
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [16]:
# Rápida exploración de nulos
df.isnull().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

## Selección de columnas y filas

In [33]:
# Visualizar columnas
df.columns
#df.shape[1] 12 columnas
#filtro una columna especifica
#df["type"]
#filtrar las columnas desde release_year
#df.loc[:, "release_year":]

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [34]:
# Observar o filtrar una columna
df["description"]

0       As her father nears the end of his life, filmm...
1       After crossing paths at a party, a Cape Town t...
2       To protect his family from a powerful drug lor...
3       Feuds, flirtations and toilet talk go down amo...
4       In a city of coaching centers known to train I...
                              ...
8802    A political cartoonist, a crime reporter and a...
8803    While living alone in a spooky town, a young g...
8804    Looking to survive in a world taken over by zo...
8805    Dragged from civilian life, a former superhero...
8806    A scrappy but poor boy worms his way into a ty...
Name: description, Length: 8807, dtype: object

In [44]:
# Observar o filtrar más de una columna
#df[["description","title"]]
df.loc[:, ["description","title"]]

                                            description                  title
0     As her father nears the end of his life, filmm...   Dick Johnson Is Dead
1     After crossing paths at a party, a Cape Town t...          Blood & Water
2     To protect his family from a powerful drug lor...              Ganglands
3     Feuds, flirtations and toilet talk go down amo...  Jailbirds New Orleans
4     In a city of coaching centers known to train I...           Kota Factory
...                                                 ...                    ...
8802  A political cartoonist, a crime reporter and a...                 Zodiac
8803  While living alone in a spooky town, a young g...            Zombie Dumb
8804  Looking to survive in a world taken over by zo...             Zombieland
8805  Dragged from civilian life, a former superhero...                   Zoom
8806  A scrappy but poor boy worms his way into a ty...                 Zubaan

[8807 rows x 2 columns]

In [53]:
# Agregamos ordenamiento
df.loc[:,["release_year","title","description"]].sort_values("release_year",  ascending = False)

,release_year,title,description
1,2021,Blood & Water,"After crossing paths at a party, a Cape Town t..."
2,2021,Ganglands,To protect his family from a powerful drug lor...
3,2021,Jailbirds New Orleans,"Feuds, flirtations and toilet talk go down amo..."
31,2021,Chicago Party Aunt,Chicago Party Aunt Diane is an idolized troubl...
30,2021,Ankahi Kahaniya,"As big city life buzzes around them, lonely so..."
...,...,...,...
8739,1943,Why We Fight: The Battle of Russia,This installment of Frank Capra's acclaimed do...
8660,1943,Undercover: How to Operate Behind Enemy Lines,This World War II-era training film dramatizes...
7790,1942,Prelude to War,Frank Capra's documentary chronicles the rise ...
8205,1942,The Battle of Midway,Director John Ford captures combat footage of ...
4250,1925,Pioneers: First Women Filmmakers*,This collection restores films from women who ...

In [55]:
# Seleccionar filas específicas
df.loc[1:5, :]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

In [58]:
# Seleccionar un subset (filas y columnas especíicas)
df.loc[1:5, ["title","description","rating"]]

,title,description,rating
1,Blood & Water,"After crossing paths at a party, a Cape Town t...",TV-MA
2,Ganglands,To protect his family from a powerful drug lor...,TV-MA
3,Jailbirds New Orleans,"Feuds, flirtations and toilet talk go down amo...",TV-MA
4,Kota Factory,In a city of coaching centers known to train I...,TV-MA
5,Midnight Mass,The arrival of a charismatic young priest brin...,TV-MA

## Filtros

### Filtros con condiciones lógicas

In [65]:
# Filtrar los registros que sean Movie
#df.query('''
 # type == "Movie"
#''')
df[df["type"] =="Movie"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [66]:
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [70]:
# Los registros cuyo campo country es Argentina
#df.query('country == "Argentina"')
df[df["country"]=="Argentina"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
275,s276,TV Show,The Kingdom,NaN,"Chino Darín, Nancy Dupláa, Joaquín Furriel, Pe...",Argentina,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...","After his running mate's murder, a controversi..."
303,s304,Movie,Esperando la carroza,Alejandro Doria,"Luis Brandoni, China Zorrilla, Antonio Gasalla...",Argentina,"August 5, 2021",1985,TV-MA,95 min,"Comedies, Cult Movies, International Movies",Cora has three sons and a daughter and she´s a...
434,s435,TV Show,Okupas,NaN,"Rodrigo de la Serna, Diego Alonso, Ariel Stalt...",Argentina,"July 20, 2021",2020,TV-MA,1 Season,"Classic & Cult TV, Crime TV Shows, Internation...","In 2000, a group of young men takes over a hou..."
673,s674,TV Show,No Time for Shame,NaN,Santiago Artemis,Argentina,"June 19, 2021",2019,TV-MA,1 Season,"International TV Shows, Reality TV, Spanish-La...","Follow Santiago Artemis, a Buenos Aires fashio..."
709,s710,TV Show,Millennials,NaN,"Nicolás Riera, Laura Laprida, Juan Manuel Guil...",Argentina,"June 16, 2021",2020,TV-MA,3 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A group of millennials copes with the pressure...
769,s770,Movie,From Stress to Happiness,"Alejandro De Grazia, Juan Stadler",NaN,Argentina,"June 3, 2021",2020,TV-G,58 min,"Documentaries, International Movies",A stressed-out documentary filmmaker goes on a...
838,s839,Movie,Soy Rada: Serendipity,Pablo Faro,Agustín Aristarán,Argentina,"May 27, 2021",2021,TV-MA,70 min,Stand-Up Comedy,The delightful Argentine comic Agustín Aristar...
1417,s1418,Movie,Al acecho,Francisco D'Eufemia,"Rodrigo de la Serna, Belen Blanco, Walter Jako...",Argentina,"January 12, 2021",2019,TV-MA,81 min,"International Movies, Thrillers","Looking for a fresh start, a park ranger gets ..."
1657,s1658,Movie,Notes for My Son,Carlos Sorín,"Valeria Bertuccelli, Esteban Lamothe, Julián S...",Argentina,"November 24, 2020",2020,TV-MA,84 min,"Dramas, International Movies","Battling terminal cancer, a woman writes a one..."
1713,s1714,Movie,Memories of a Teenager,Lucas Santa Ana,"Renato Quattordio, Malena Narvay, Thomás Leper...",Argentina,"November 12, 2020",2019,TV-MA,97 min,"Dramas, International Movies, LGBTQ Movies","To cope with a friend's death, a teen blogs ab..."
1733,s1734,TV Show,Carmel: Who Killed Maria Marta?,Alejandro Hartmann,NaN,Argentina,"November 5, 2020",2020,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...","A woman is found dead in her bathtub, with a p..."
1792,s1793,Movie,Guillermo Vilas: Settling the Score,Matías Gueilburt,NaN,Argentina,"October 27, 2020",2020,TV-14,95 min,"Documentaries, International Movies, Sports Mo...",An Argentine journalist strives to prove that ...
1876,s1877,Movie,Palermo Hollywood,Eduardo Pinto,"Brian Maya, Matías Desiderio, Manuela Pal, Azu...",Argentina,"October 8, 2020",2004,TV-MA,106 min,"Dramas, International Movies",A pair of petty criminals from different backg...
1917,s1918,TV Show,Secreto bien guardado,NaN,"Oriana Sabatini, Victorio D'Alessandro, Noemí ...",Argentina,"October 1, 2020",2019,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, Spa...","In 1940 Argentina, a Jewish 17-year-old on vac..."
2034,s2035,Movie,So Much Love to Give,Marcos Carnevale,"Adrián Suar, Soledad Villamil, Gabriela Toscan...",Argentina,"September 9, 2020",2020,TV-14,108 min,"Comedies, International Movies, Music & Musicals",Fernando is a family man — equally committed t...
2111,s2112,Movie,The Crimes That Bind,Sebastián Schindel,"Cecilia Roth, Miguel Ángel Solá, Benjamín Amad...",Argentina,"August 20, 2020",2020,TV-14,100 min,"Dramas, International Movies",When her son is accused of raping and trying t...
2465,s2466,Movie,Intuition,Alejandro Montiel,"Luisana Lopilato, Joaquín Furriel, Rafael Ferr...",Argentina,"May 28, 2020",2020,TV-MA,116 min,"Dramas, International Movies, Thrillers",Police officer Pipa works on her first big cas...
2565,s2566,TV Show,Almost Happy,Hernán Guerschuny,"Sebastián Wainraich, Natalie Pérez, Santiago K...",Argentina,"May 2, 2020",2020,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","Sebastián is a radio show host of modest fame,..."
2786,s2787,Movie,A Life of Speed: The Juan Manuel Fangio Story,Francisco Macri,NaN,Argentina,"March 20, 2020",2020,TV-14,93 min,"Documentaries, International Movies, Sports Mo...","Juan Manuel Fangio was the Formula One king, w..."
2894,s2895,TV Show,Puerta 7,NaN,"Dolores Fonzi, Esteban Lamothe, Carlos Belloso...",Argentina,"February 21, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A determined woman works to rid an Argentine s...
3266,s3267,Movie,GO! The Unforgettable Party,Mauro Scandolari,"Pilar Pascual, José Gimenez Zapiola, Renata To...",Argentina,"November 15, 2019",2019,TV-PG,60 min,"Children & Family Movies, Music & Musicals",Mía's vacation with her dad is disrupted by th...
3354,s3355,Movie,Grego Rossello: Disculpe las molestias,Juani Libonatti,Grego Rossello,Argentina,"October 31, 2019",2019,TV-MA,65 min,Stand-Up Comedy,Argentine comedian Grego Rossello takes the st...
3375,s3376,TV Show,Monzón: A Knockout Blow,NaN,"Jorge Román, Mauricio Paniagua, Carla Quevedo,...",Argentina,"October 25, 2019",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This dramatization tells the story of Argentin...
3483,s3484,TV Show,El Marginal,NaN,"Juan Minujín, Martina Gusman, Gerardo Romano, ...",Argentina,"September 27, 2019",2019,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, Spanis...","While investigating a kidnapping, an ex-cop se..."
3576,s3577,TV Show,Apache: The Life of Carlos Tevez,NaN,"Balthazar Murillo, Vanesa González, Alberto Aj...",Argentina,"August 16, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This gritty dramatization of the life of Carlo...
3641,s3642,Movie,The Son,Sebastián Schindel,"Joaquín Furriel, Martina Gusmán, Luciano Cácer...",Argentina,"July 26, 2019",2019,TV-MA,93 min,"Dramas, Independent Movies, International Movies","In this psychological thriller, painter Lorenz..."
3681,s3682,Movie,"River, el más grande siempre","Marcelo Altmark, Mariano Mucci, Luis A. Scalella",NaN,Argentina,"July 5, 2019",2019,TV-G,105 min,"Documentaries, International Movies, Sports Mo...",Experience the highlights of Argentine soccer ...
3722,s3723,TV Show,Go! Live Your Way,NaN,"Pilar Pascual, Renata Toscano, José Giménez Za...",Argentina,"June 21, 2019",2019,TV-PG,2 Seasons,"Kids' TV, Spanish-Language TV Shows, Teen TV S...",Charismatic Mía gets a scholarship to an elite...
3823,s3824,TV Show,"Heidi, bienvenida a casa",NaN,"Chiara Francia, Mercedes Lambre, Victorio D'Al...",Argentina,"May 15, 2019",2017,TV-Y,1 Season,"Kids' TV, Spanish-Language TV Shows","Inspired by the classic novel, this telenovela..."
4111,s4112,TV Show,The Kirlian Frequency,NaN,"Nicolás Van de Moortele, Letizia Denise Bloisi...",Argentina,"February 15, 2019",2017,TV-14,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the midnight hour, a lone DJ broadcasts the..."
4173,s4174,Movie,Just Love,"Andy Caballero, Diego Corsini","Franco Masini, Yamila Saud, Victorio D'Alessan...",Argentina,"January 24, 2019",2018,TV-MA,96 min,"Dramas, International Movies, Music & Musicals",Inspired by his love affair with a conservativ...
4430,s4431,TV Show,Creators,NaN,"Fabio Aste, Héctor Segura, Sebastian Rosas",Argentina,"November 1, 2018",2015,TV-Y,2 Seasons,"Kids' TV, Spanish-Language TV Shows",Two brilliant scientists discover the hidden v...
4781,s4782,Movie,Luciano Mellera: Infantiloide,"Raúl Campos, Jan Suter",Luciano Mellera,Argentina,"July 6, 2018",2018,TV-14,66 min,Stand-Up Comedy,Argentina's Luciano Mellera emphasizes the hum...
4849,s4850,Movie,Fernando Sanjiao: Hombre,"Raúl Campos, Jan Suter",Fernando Sanjiao,Argentina,"May 25, 2018",2018,TV-MA,63 min,Stand-Up Comedy,Argentine actor and comedian Fernando Sanjiao ...
4940,s4941,Movie,Todo lo que sería Lucas Lauriente,"Raúl Campos, Jan Suter",Lucas Lauriente,Argentina,"April 6, 2018",2018,TV-MA,78 min,Stand-Up Comedy,"In his stand-up set, Argentine comic Lucas Lau..."
4978,s4979,TV Show,Edha,NaN,"Juana Viale, Andrés Velencoso, Delfina Chaves,...",Argentina,"March 16, 2018",2018,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","Revenge, passion and dark secrets push a succe..."
5001,s5002,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",Malena Pichot,Argentina,"March 2, 2018",2018,TV-MA,51 min,Stand-Up Comedy,An Argentine comedian espouses the values of f...
5034,s5035,Movie,Agustín Aristarán: Soy Rada,Mariano Baez,Agustín Aristarán,Argentina,"February 16, 2018",2018,TV-MA,60 min,Stand-Up Comedy,"Argentine comedian Agustín ""Radagast"" Aristará..."
5062,s5063,Movie,Sebastián Marcelo Wainraich,"Raúl Campos, Jan Suter",Sebastián Marcelo Wainraich,Argentina,"January 26, 2018",2018,TV-MA,49 min,Stand-Up Comedy,Argentine comedian Sebastián Wainraich highlig...
5114,s5115,Movie,Desire,Diego Kaplan,"Carolina Ardohain, Mónica Antonópulos, Guilher...",Argentina,"December 21, 2017",2017,TV-MA,94 min,"Dramas, International Movies, Romantic Movies",A young woman arrives at her estranged sister'...
5314,s5315,Movie,Todo Sobre El Asado,"Mariano Cohn, Gastón Duprat",El Negro Álvarez,Argentina,"September 1, 2017",2016,TV-MA,86 min,"Documentaries, International Movies",This quirky examination of Argentina's culture...
5551,s5552,Movie,The Tenth Man,Daniel Burman,"Alan Sabbagh, Julieta Zylberberg, Usher Barilk...",Argentina,"April 1, 2017",2016,TV-MA,81 min,"Dramas, International Movies",After spending much of his adult life in New Y...
6004,s6005,Movie,"27, el club de los malditos",Nicanor Loreti,"Diego Capusotto, Sofía Gala, Daniel Aráoz, Wil...",Argentina,"May 1, 2018",2018,TV-MA,82 min,"Action & Adventure, Comedies, International Mo...",After a musician dies under suspicious circums...
6082,s6083,Movie,Abzurdah,Daniela Goggi,"Eugenia Suárez, Esteban Lamothe, Gloria Carrá,...",Argentina,"August 25, 2016",2015,TV-MA,90 min,"Dramas, International Movies",A disenfranchised 16-year-old girl connects to...
6400,s6401,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
6482,s6483,Movie,Chronicle of an Escape,Israel Adrián Caetano,"Rodrigo de la Serna, Pablo Echarri, Nazareno C...",Argentina,"June 15, 2018",2006,R,104 min,"Dramas, International Movies, Thrillers",Soccer goalie Claudio Tamburrini is kidnapped ...
6552,s6553,Movie,Daemonium,Pablo Parés,"Walter Cornás, Dany Casco, Caro Angus, Rocío R...",Argentina,"December 20, 2016",2015,NR,115 min,"Action & Adventure, Horror Movies, Internation...",In a realm where magic and technology intersec...
6705,s6706,Movie,Esperando La Carroza,Alejandro Doria,"Luis Brandoni, China Zorrilla, Antonio Gasalla...",Argentina,"July 15, 2018",1985,NR,95 min,"Comedies, Cult Movies, International Movies",Cora has three sons and a daughter and she´s a...
6974,s6975,TV Show,Historia de un clan,NaN,"Alejandro Awada, Cecilia Roth, Chino Darín, Na...",Argentina,"January 13, 2017",2015,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This drama based on a true story follows the P...
7034,s7035,Movie,Hypersomnia,Gabriel Grieco,"Yamila Saud, Gerardo Romano, Jimena Barón, Van...",Argentina,"June 8, 2017",2016,TV-MA,84 min,"Horror Movies, International Movies, Thrillers",A young actress rehearsing for a play about hu...
7250,s7251,Movie,La Última Fiesta,"Leandro Mark, Nicolás Silbert","Nicolás Vázquez, Alan Sabbagh, Benjamín Amadeo...",Argentina,"February 1, 2017",2016,TV-MA,104 min,"Comedies, International Movies",Three best buddies are thrown into a wild chas...
7358,s7359,Movie,Lucha: Playing the Impossible,Ana Quiroga,Luciana Aymar,Argentina,"July 15, 2018",2016,TV-PG,98 min,"Documentaries, International Movies, Sports Mo...","Known simply as ""Lucha,"" field hockey player L..."
7421,s7422,Movie,Mater,Pablo D'Alo Abba,"Lautaro Perotti, Tamara Kiper, Inda Lavalle, M...",Argentina,"August 1, 2018",2017,TV-MA,80 min,"Dramas, Independent Movies, International Movies",A single man in his 30s overwhelmed by his dom...
7745,s7746,Movie,"Pizza, birra, faso","Israel Adrián Caetano, Bruno Stagnaro","Héctor Anglada, Jorge Sesán, Pamela Jordán, Ad...",Argentina,"March 15, 2018",1998,TV-MA,81 min,"Dramas, International Movies",A group of hardscrabble young thieves in Argen...
7800,s7801,TV Show,Psiconautas,NaN,"Guillermo Toledo, Gabriel Goity, Florencia Peñ...",Argentina,"April 15, 2018",2016,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",A Spanish con man masquerades as a therapist a...
8185,s8186,Movie,The Aerial,Esteban Sapir,"Rafael Ferro, Sol Moreno, Jonathan Sandor, Ale...",Argentina,"April 1, 2018",2007,TV-MA,99 min,"Dramas, International Movies, Sci-Fi & Fantasy","In the City Without a Voice, only faceless sin..."

In [86]:
# Los registros (movies/series) que cuyo año de "release" es anterior al 2020
df.query('type in ["Movie",  "series" ] and release_year < 2020 ').sort_values("release_year", ascending = False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
90,s91,Movie,Paradise Hills,Alice Waddington,"Emma Roberts, Danielle Macdonald, Awkwafina, E...","Spain, United States","September 9, 2021",2019,TV-MA,95 min,"Sci-Fi & Fantasy, Thrillers",Uma wakes up in a lush tropical facility desig...
7683,s7684,Movie,Our Godfather,"Mark Franchetti, Andrew Meier",Tommaso Buscetta,United Kingdom,"September 10, 2019",2019,TV-MA,93 min,"Documentaries, International Movies","In 1986, Tommaso Buscetta became the first top..."
8718,s8719,Movie,Westside vs. the World,Michael Fahey,"Ron Perlman, Louie Simmons",NaN,"August 9, 2019",2019,TV-MA,96 min,"Documentaries, Sports Movies",A look into the journey of influential strengt...
7799,s7800,Movie,Prosecuting Evil: The Extraordinary World of B...,Barry Avrich,Ben Ferencz,Canada,"June 1, 2019",2019,TV-MA,83 min,Documentaries,"A gripping profile of Ben Ferencz, the last su..."
7807,s7808,Movie,Q Ball,Michael Tolajian,NaN,United States,"March 11, 2020",2019,TV-MA,96 min,"Documentaries, Sports Movies","At San Quentin State Prison, hardened convicts..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...

In [107]:
# Verificar el dtype de la columna "release_year"
df.release_year.dtype
df.date_added.dtype

dtype('<M8[ns]')

In [115]:
# Los registros (movies/series) que cuyo date_added es anterior al 2020
df.loc[df["date_added"].dt.year < 2020, "date_added":].sort_values("date_added", ascending= False)

,date_added,release_year,rating,duration,listed_in,description
3077,2019-12-31,2019,TV-14,110 min,"Horror Movies, International Movies, Thrillers","After losing their first child in an accident,..."
7830,2019-12-31,2005,TV-14,154 min,"Comedies, Dramas, International Movies",A small-town cook moves to London to earn a li...
6604,2019-12-31,2007,TV-14,128 min,"Action & Adventure, Comedies, International Mo...","Tipped off about buried money in Goa, four ne’..."
6577,2019-12-31,2006,TV-14,97 min,"Independent Movies, International Movies, Thri...",A surgeon’s perfect life is rattled when his d...
6485,2019-12-31,1975,TV-PG,127 min,"Classic Movies, Comedies, International Movies",Jealous of the high regard in which his new wi...
...,...,...,...,...,...,...
7370,2010-11-01,1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott..."
5955,2009-11-18,2009,TV-MA,29 min,Horror Movies,"After committing suicide, a washed-up rocker r..."
5956,2009-05-05,2007,TV-MA,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...
6611,2008-02-04,2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo..."
5957,2008-01-01,2006,TV-MA,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea..."

In [92]:
# Verificar el dtype de la columna "date_added"
df.date_added.dtype

dtype('O')

In [105]:
# Convertimos el dtype de object a datetime
#df["date_added"] = pd.to_datetime(df["date_added"].str.strip(), format="%B %d, %Y")
df["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

### Combinación de condiciones (&, |)

In [ ]:
# Filtrar por más de una condición df[(df["campo1" == "valor"]) &| ("campo2" > valor)]

In [ ]:
# Usamos contains() para texto

In [ ]:
# Jugar un poco con el dataframe con las películas Argentinas

In [ ]:
# Usamos isin() para listas
# Supongamos que queremos filtrar las películas de 3 países

In [ ]:
# Uso de query - más legible para condiciones complejas
# Permite escribir una condicion como si fuera una consulta sql